version: '3'

services:
  database:
    image: postgres

    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: skarbnik_admin
      POSTGRES_DB: skarbnik_db

    ports:
    - 5432:5432

